CREATE TABLE `borrower_contact` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `loan_no` varchar(40) NOT NULL COMMENT '贷款业务号',
  `relationship` varchar(10) DEFAULT NULL COMMENT '与该客户关系',
  `contact_person_name` varchar(25) DEFAULT NULL COMMENT '姓名',
  `contact_person_id_type` varchar(10) DEFAULT NULL COMMENT '证件类型',
  `contact_person_id_no` varchar(50) DEFAULT NULL COMMENT '证件号码',
  `contact_person_phone_no` varchar(16) DEFAULT NULL COMMENT '联系电话',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `borrower_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `created_time` datetime DEFAULT NULL,
  `updated_time` datetime DEFAULT NULL,
  `loan_no` varchar(40) NOT NULL COMMENT '贷款业务号',
  `name` varchar(25) NOT NULL COMMENT '姓名',
  `id_type` varchar(10) NOT NULL COMMENT '证件类型',
  `id_no` varchar(50) NOT NULL COMMENT '证件号码',
  `gender` varchar(10) DEFAULT NULL COMMENT '性别',
  `date_of_birth` date DEFAULT NULL COMMENT '出生日期',
  `marital_status` varchar(10) DEFAULT NULL COMMENT '婚姻状况',
  `highest_academic_credential` varchar(10) DEFAULT NULL COMMENT '最高学历',
  `highest_academic_degree` varchar(10) DEFAULT NULL COMMENT '最高学位',
  `home_phone_no` varchar(16) DEFAULT NULL COMMENT '住宅电话',
  `mobile_phone_no` varchar(25) DEFAULT NULL COMMENT '手机号码',
  `enterprise_phone_no` varchar(30) DEFAULT NULL COMMENT '单位电话',
  `email` varchar(60) DEFAULT NULL COMMENT '电子邮箱',
  `mailing_district` varchar(6) DEFAULT NULL COMMENT '通讯地址所在区域',
  `mailing_address` varchar(60) DEFAULT NULL COMMENT '通讯地址',
  `mailing_zip_code` varchar(60) DEFAULT NULL COMMENT '通讯地址邮政编码',
  `domicile_address` varchar(60) DEFAULT NULL COMMENT '户籍地址',
  `enterprise_industry` varchar(10) DEFAULT NULL COMMENT '单位所属行业',
  `occupation` varchar(60) DEFAULT NULL COMMENT '职业',
  `enterprise_name` varchar(60) DEFAULT NULL COMMENT '单位名称',
  `enterprise_address` varchar(60) DEFAULT NULL COMMENT '单位地址',
  `annual_income` decimal(19,2) DEFAULT NULL,
  `current_enterprise_start_working_year` date DEFAULT NULL,
  `enterprise_zip_code` varchar(60) DEFAULT NULL,
  `position` varchar(10) DEFAULT NULL,
  `professional_title` varchar(10) DEFAULT NULL,
  `residential_address` varchar(60) DEFAULT NULL,
  `residential_district` varchar(6) DEFAULT NULL,
  `residential_status` varchar(10) DEFAULT NULL,
  `residential_zip_code` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_n_ct_ci` (`name`,`id_type`,`id_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `borrower_spouse` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `spouse_enterprise` varchar(60) DEFAULT NULL,
  `spouse_id_no` varchar(50) NOT NULL,
  `spouse_id_type` varchar(10) NOT NULL,
  `spouse_name` varchar(25) NOT NULL,
  `spouse_phone_no` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `customer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `annual_income` decimal(19,2) DEFAULT NULL,
  `current_enterprise_start_working_year` date DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `domicile_address` varchar(60) DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `enterprise_address` varchar(60) DEFAULT NULL,
  `enterprise_industry` varchar(10) DEFAULT NULL,
  `enterprise_name` varchar(60) DEFAULT NULL,
  `enterprise_phone_no` varchar(30) DEFAULT NULL,
  `enterprise_zip_code` varchar(60) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `highest_academic_credential` varchar(10) DEFAULT NULL,
  `highest_academic_degree` varchar(10) DEFAULT NULL,
  `home_phone_no` varchar(16) DEFAULT NULL,
  `id_no` varchar(50) NOT NULL,
  `id_type` varchar(10) NOT NULL,
  `mailing_address` varchar(60) DEFAULT NULL,
  `mailing_district` varchar(6) DEFAULT NULL,
  `mailing_zip_code` varchar(60) DEFAULT NULL,
  `marital_status` varchar(10) DEFAULT NULL,
  `mobile_phone_no` varchar(25) DEFAULT NULL,
  `name` varchar(25) NOT NULL,
  `occupation` varchar(60) DEFAULT NULL,
  `position` varchar(10) DEFAULT NULL,
  `professional_title` varchar(10) DEFAULT NULL,
  `residential_address` varchar(60) DEFAULT NULL,
  `residential_district` varchar(6) DEFAULT NULL,
  `residential_status` varchar(10) DEFAULT NULL,
  `residential_zip_code` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_n_ct_ci` (`name`,`id_type`,`id_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `customer_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `customer_id` bigint(20) NOT NULL,
  `customer_json` longtext NOT NULL,
  `end_time` datetime DEFAULT NULL,
  `id_no` varchar(50) NOT NULL,
  `id_type` varchar(10) NOT NULL,
  `name` varchar(25) NOT NULL,
  `reason_for_change` varchar(60) DEFAULT NULL,
  `start_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `customer_relation_ship` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `end_date` date NOT NULL,
  `from_customer_id` bigint(20) NOT NULL,
  `relation_ship_type` varchar(10) NOT NULL,
  `start_date` date NOT NULL,
  `to_customer_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `database_file` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `content_type` varchar(255) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `file_content` longblob,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `lending_record` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `bank_trans_code` varchar(40) NOT NULL,
  `collection_account_no` varchar(60) NOT NULL,
  `collection_account_user` varchar(30) NOT NULL,
  `collection_org_no` varchar(60) NOT NULL,
  `lending_amount` decimal(10,2) NOT NULL,
  `lending_code` varchar(40) NOT NULL,
  `lending_date` date NOT NULL,
  `loan_account_no` varchar(60) NOT NULL,
  `loan_account_user` varchar(30) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `loan_org_no` varchar(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_ldc` (`lending_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `bene_account_branch` varchar(60) NOT NULL,
  `bene_account_name` varchar(30) NOT NULL,
  `bene_account_no` varchar(60) NOT NULL,
  `debit_account_bank` varchar(60) NOT NULL,
  `debit_account_name` varchar(30) NOT NULL,
  `debit_account_no` varchar(60) NOT NULL,
  `loan_issuer_account_bank` varchar(60) NOT NULL,
  `loan_issuer_account_name` varchar(30) NOT NULL,
  `loan_issuer_account_no` varchar(60) NOT NULL,
  `loan_issuing_financial_institution` varchar(60) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `loan_repayment_bene_account_bank` varchar(60) NOT NULL,
  `loan_repayment_bene_account_name` varchar(30) NOT NULL,
  `loan_repayment_bene_account_no` varchar(60) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_account_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `end_time` datetime DEFAULT NULL,
  `loan_account_id` bigint(20) DEFAULT NULL,
  `loan_account_json` longtext NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `reason_for_change` varchar(60) NOT NULL,
  `start_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_guarantor` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `email` varchar(60) DEFAULT NULL,
  `id_no` varchar(50) NOT NULL,
  `id_type` varchar(10) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `mobile_phone_no` varchar(25) DEFAULT NULL,
  `name` varchar(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_image_doc` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `img_name` varchar(20) NOT NULL,
  `img_path` varchar(255) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `loan_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `apply_date` date NOT NULL,
  `business_type` varchar(10) NOT NULL,
  `currency` varchar(10) NOT NULL,
  `end_date` date NOT NULL,
  `forfeit_rate` decimal(10,2) NOT NULL,
  `guarantee_contract_no` varchar(40) DEFAULT NULL,
  `loan_amount` decimal(10,2) NOT NULL,
  `loan_contract_no` varchar(40) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `loan_rate` decimal(10,2) NOT NULL,
  `pledge_contract_no` varchar(40) DEFAULT NULL,
  `pledge_info` varchar(255) DEFAULT NULL,
  `pledge_type` varchar(10) DEFAULT NULL,
  `product_name` varchar(40) NOT NULL,
  `repayment_freq` varchar(10) NOT NULL,
  `repayment_term` varchar(10) NOT NULL,
  `repayment_type` varchar(10) NOT NULL,
  `start_date` date NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_lc` (`loan_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `operator` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date_of_birth` date DEFAULT NULL,
  `email` varchar(60) NOT NULL,
  `enterprise_phone_no` varchar(30) NOT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `id_no` varchar(50) NOT NULL,
  `id_type` varchar(10) NOT NULL,
  `memo` varchar(255) DEFAULT NULL,
  `mobile_phone_no` varchar(25) NOT NULL,
  `operator_code` varchar(40) NOT NULL,
  `operator_name` varchar(25) NOT NULL,
  `operator_type` varchar(30) NOT NULL,
  `org_id` bigint(20) NOT NULL,
  `password` varchar(60) NOT NULL,
  `status` varchar(30) NOT NULL,
  `username` varchar(25) NOT NULL,
  `version` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_optc` (`operator_code`),
  UNIQUE KEY `uidx_usn` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `organization` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `org_name` varchar(25) NOT NULL,
  `org_type` varchar(30) NOT NULL,
  `version` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `repayment` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `bank_trans_code` varchar(40) NOT NULL,
  `fee_payment` decimal(10,2) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `normal_interest_payment` decimal(10,2) NOT NULL,
  `normal_principle_repayment` decimal(10,2) NOT NULL,
  `overdue_interest_payment` decimal(10,2) NOT NULL,
  `overdue_interest_penalty_interest_payment` decimal(10,2) NOT NULL,
  `overdue_principle_penalty_interest_payment` decimal(10,2) NOT NULL,
  `overdue_principle_repayment` decimal(10,2) NOT NULL,
  `repayment_code` varchar(40) NOT NULL,
  `repayment_date` date NOT NULL,
  `repayment_type` varchar(10) NOT NULL,
  `total_repayment_amount` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_rpc` (`repayment_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `repayment_plan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `current_periodclearing_status` bit(1) NOT NULL,
  `interest_paid` decimal(10,2) NOT NULL,
  `interest_penalty_interest_paid` decimal(10,2) NOT NULL,
  `interest_penalty_interest_to_be_paid` decimal(10,2) NOT NULL,
  `interest_to_be_paid` decimal(10,2) NOT NULL,
  `loan_no` varchar(40) NOT NULL,
  `loan_value_date` date NOT NULL,
  `period` int(11) NOT NULL,
  `principle_penalty_interest_paid` decimal(10,2) NOT NULL,
  `principle_penalty_interest_to_be_paid` decimal(10,2) NOT NULL,
  `principle_repaid` decimal(10,2) NOT NULL,
  `principle_to_be_repaid` decimal(10,2) NOT NULL,
  `repayment_date_planned` date NOT NULL,
  `total_fee_paid` decimal(10,2) NOT NULL,
  `total_fee_to_be_paid` decimal(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uidx_lc_s` (`loan_no`,`period`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `repayment_plan_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `created_time` datetime DEFAULT NULL,
  `lower_org_id` bigint(20) NOT NULL,
  `updated_time` datetime DEFAULT NULL,
  `upper_org_id` bigint(20) NOT NULL,
  `version` int(11) NOT NULL,
  `end_time` datetime DEFAULT NULL,
  `loan_no` varchar(40) NOT NULL,
  `reason_for_change` varchar(60) DEFAULT NULL,
  `repayment_plan_id` bigint(20) NOT NULL,
  `repayment_plan_json` longtext NOT NULL,
  `start_time` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
